spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password: root
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
#  security:
#    user:
#      name: user
#      password: user
#      roles: ADMIN